### ISSUE TITLE
Support git deps with build tool

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1338]
Gleam only, no need for rebar3 currently

https://github.com/elixir-lang/elixir/blob/79cd891eb86ecb7654a7acdb63769cfdd950a5c0/lib/mix/lib/mix/scm/git.ex

- [x] Update gleam.toml to include git deps. Will require a fancy serde deserializer.
- [ ] Download top level git deps
- [ ] Parse gleam.toml for them
- [ ] Add info to manifest
- [ ] Integrate into the version resolver
- [ ] Assert there are no git deps when publishing

Anything else? Can't think of anything.

## Config

```toml
[deps]
short_hex_package = "~> 1.0"
long_hex_package = { version = "~> 1.0" }
git_package = { git = "git@github.com:gleam-lang/stdlib.git", ref = "284b9f0" }

# We could have this shortcut too
github_package = { github = "gleam-lang/stdlib", ref = "284b9f0" }
```
