### ISSUE TITLE
Issue including gpb in pure gleam project. 

### ISSUE THREAD

**Issue by bwireman** [gleam-lang/gleam#1464]
- gleam version: 0.19.0
- OS: Linux 5.14.21-210.current (Solus x86_64)
- OTP: 24

I'm working on a wrapper for [`gpb`](https://github.com/tomas-abrahamsson/gpb) with useful Gleam types and I'm seeing this issue when trying `gleam test` or `gleam run`

```
=INFO REPORT==== 16-Jan-2022::12:52:55.547199 ===
    application: gleeunit
    exited: stopped
    type: temporary

=INFO REPORT==== 16-Jan-2022::12:52:55.565329 ===
    application: gleam_stdlib
    exited: stopped
    type: temporary

exception error: no match of right hand side value 
                 {error,{gpb,{"no such file or directory","gpb.app"}}}
```

```toml
# gleam.toml
name = "example"
version = "0.1.0"

[dependencies]
gleam_stdlib = "~> 0.19"
gpb = "~> 4.19"

[dev-dependencies]
gleeunit = "~> 0.6"
```

```toml
# manifest.toml
packages = [
  { name = "gleam_stdlib", version = "0.19.3", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "CA579C2FF0621E93FF6EFEF61BAFFCF0505732BA073F616E28878042F1A1F401" },
  { name = "gleeunit", version = "0.6.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleeunit", source = "hex", outer_checksum = "77701A5E5A565727E1EEAC9196FB878D544049B6331CD0305B5A69699135EA1C" },
  { name = "gpb", version = "4.19.2", build_tools = ["rebar3", "make"], requirements = [], otp_app = "gpb", source = "hex", outer_checksum = "3F4CB7F263E94675A598501A6DC96EC17F93ECB28C29BEA3BEA3A71C53A3317A" },
]

[requirements]
gleam_stdlib = "~> 0.19"
gleeunit = "~> 0.6"
gpb = "~> 4.19"
```
