### ISSUE TITLE
Customizable source directories for `gleam build`

### ISSUE THREAD

**Issue by aslilac** [gleam-lang/gleam#1556]
Based on a [conversation in Discord](https://discord.com/channels/768594524158427167/768594524158427170/951658093245263913)

./src/ is a great default, but occasionally you run into constraints that require something a bit more customizable.

In gleam.toml, we could potentially let you specify something like...
```toml
source = "./api/"
```

We might even want to let you specify multiple source directories...
```toml
source = ["./api/", "./lib/"]
```
...which would unfortunately be a bit ambiguous. Should `import a/b` resolve to ./api/a/b.gleam or ./lib/a/b.gleam if there's a conflict? Maybe we just throw an error if it could be resolved more than one way?

Another solution could be a "shared root" similar to what [TypeScript does](https://www.typescriptlang.org/tsconfig#rootDir)
```toml
# Must be a parent of all modules
sourceRoot = "./" 
# These paths should probably 
modules = ["api", "lib"] # These would probably be "Gleam paths" and not fs paths.
```

...which in Gleam could then allow you to...

```gleam
import lib/some/shared/logic.{Whatever}

...
```

...where the prefix makes imports unambiguous.
