### ISSUE TITLE
Do not download optional dependencies by default

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#1964]
Start a new project with the following deps:

```toml
[dependencies]
gleam_stdlib = "~> 0.25"
phoenix = "~> 1.6.15"

[dev-dependencies]
gleeunit = "~> 0.7"
```

Use `gleam deps download` to get the deps. Observe `gleam deps list`:

```
castore 1.0.0
cowboy 2.9.0
cowboy_telemetry 0.4.0
cowlib 2.11.0
decimal 2.0.0
gleam_stdlib 0.26.0
gleeunit 0.9.0
jason 1.4.0
mime 2.0.3
phoenix 1.6.15
phoenix_html 3.2.0
phoenix_pubsub 2.1.1
phoenix_template 1.0.0
phoenix_view 2.0.2
plug 1.14.0
plug_cowboy 2.6.0
plug_crypto 1.2.3
ranch 1.8.0
telemetry 1.2.1
```

There is a whole bunch of stuff here. But looking at the Phoenix package, jason and plug_cowboy are optional but still included. Indirectly a lot of other stuff is pulled like cowboy, ranch, phoenix_html, decimal… I guess the default should be to _not_ download optional deps.
