### ISSUE TITLE
Add `tags` to property to `gleam.toml`

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2044]
- could be used by hex.pm
- can be used by a gleam package search engine
- would be used by `gleam docs build` to inject `<meta> keywords` tag into html layouts

## Examples

```toml
name = "gleam_stdlib"
version = "0.27.0"
licences = ["Apache-2.0"]
description = "A standard library for the Gleam programming language"
tags = ["standard library", "erlang ffi", "javascript ffi"]
#...
```

```toml
name = "glychee"
version = "0.2.7"
licences = ["Apache-2.0"]
description = "Glychee: Easy access to Elixir's benchee from Gleam!"
tags = ["benchmark", "benchmarking", "test", "testing", "performance", "analytics", "erlang ffi", "elixir"]
#...
```
