### ISSUE TITLE
Statically link on Windows

### ISSUE THREAD

**Issue by MarkTiedemann** [gleam-lang/gleam#2107]
When downloading and running `gleam.exe` on a fresh Windows 10, it crashes with the following error message: _The program can't start because VCRUNTIME140.dll is missing from your computer._

I believe this is because `gleam.exe` is dynamically linked to the MSVC runtime so, in order to run Gleam, users will have to install a Visual C++ Redistributable first (which is not mentioned in the documentation).

**Comment by lpil** [comment]
Thanks for the report. What do other native projects do on Windows here?

**Comment by MarkTiedemann** [comment]
Linking the runtime statically.

Don't know much about Rust, but I believe this can be done via `.cargo/config` / `RUSTFLAGS`:

```toml
# Copied from https://github.com/denoland/deno/blob/main/.cargo/config.toml#L2

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
```
