### ISSUE TITLE
manifest.toml uses absolute paths for path deps

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2182]
Follows on from https://github.com/gleam-lang/gleam/pull/2153

These need to be relative.

```toml
packages = [
  { name = "project_b", version = "0.1.0", build_tools = ["gleam"], requirements = ["project_d"], source = "local", path = "/Users/louis/src/gleam/gleam/test/project_path_deps/project_b" },
]
```

**Comment by NthTensor** [comment]
I have a fix for this in the works. Having to thread project paths into a bunch more places.

**Comment by xhh** [comment]
Relative path dev does not work on Windows:

```toml
packages = [
# ...
{ name = "shared", version = "1.0.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], source = "local", path = "//?/D:/git/my_app/shared" }, # <=====
# ...
]

[requirements]
shared = { path = "../shared" }
mist = { version = "~> 0.17" }
wisp = { version = "~> 0.13" }
# ...
```

It doesn't hurt when developing locally, but won't work when e.g. deploying with Docker.
