### ISSUE TITLE
Crash when adding lustre_http to lustre@4.0.0-rc.2

### ISSUE THREAD

**Issue by greenfork** [gleam-lang/gleam#2673]
I have built a gleam compiler from the latest main by running `make install`. `gleam --version` shows 1.0.0 so I'm unsure whether I managed to build the latest version or it is still 1.0.0.

How to reproduce:

```
gleam new lustre_httpbug
cd lustre_httpbug/
# edit gleam.toml to have a dependency lustre = "4.0.0-rc.2"
gleam add lustre_http
```

crashes with this message:

```
  Resolving versions
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
and include this error message with your report.

Panic: /home/grfork/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pubgrub-0.2.1/src/internal/partial_solution.rs:131
	add_derivation should not be called after a decision
Gleam version: 1.0.0
Operating system: linux

If you can also share your code and say what file you were editing or any
steps to reproduce the crash that would be a great help.

You may also want to try again with the `GLEAM_LOG=trace` environment
variable set.
```

The log with `trace` is attached in a file.

[log.txt](https://github.com/gleam-lang/gleam/files/14564077/log.txt)

**Comment by greenfork** [comment]
The problem seems to be in the `gleam_json` dependency, it is locked at `~> 0.7` while the first version is available. So this crashes:

```toml
[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "4.0.0-rc.2"
gleam_json = "~> 0.7"
lustre_http = "~> 0.5.1"
```

but this resolves fine:

```toml
[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "4.0.0-rc.2"
gleam_json = "~> 1.0"
lustre_http = "~> 0.5.1"
```

if we manually change the gleam_json version.
