### ISSUE TITLE
`gleam new` overwrites `.gitignore`.

### ISSUE THREAD

**Issue by computerscience-person** [gleam-lang/gleam#2685]
I'm using gleam for the first time inside NixOS with [devenv](https://devenv.sh), and `devenv` scaffolds the project directory with its own `.gitignore`. However, when using `gleam new` in a directory with an existing `.gitignore`, it needs to delete the old `.gitignore`, or the command just fails. Should this be the behavior of `gleam new`? Or should I just scaffold the project manually? If so, is there a guide as to doing the scaffolding manually?

**Comment by lpil** [comment]
Hello! That's the intended behaviour of `gleam new`, yes. If you want to make a Gleam project manually then you can make this `gleam.toml`.

```toml
name = "app"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
```

The documentation for this can be found here: <https://gleam.run/writing-gleam/gleam-toml/>
