### ISSUE TITLE
Consider setting up Dependabot for Cargo

### ISSUE THREAD

**Issue by sobolevn** [gleam-lang/gleam#2803]
You already have a `dependabot.yml` file: https://github.com/gleam-lang/gleam/blob/efc519c65fcf23dd1c0d9e890efe0a5f9260c021/.github/dependabot.yml#L4

And there are many outdate dependencies in `Cargo.toml`s, so maybe it is a good idea to bump them automatically?

It would be something like:

```
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
```

+ several similar entries for submodules.
Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem (grep for `cargo`)

This way it is easier to spot changes that affect the project.
On the other hand, it increases the noise from the project.

If you want to try that, I can send a PR.
