### ISSUE TITLE
manifest.toml uses absolute paths for relative path devs on Windows

### ISSUE THREAD

**Issue by xhh** [gleam-lang/gleam#2837]
An example *manifest.toml* with a relative path dep `shared = { path = "../shared" }`:

```toml
packages = [
# ...
{ name = "shared", version = "1.0.0", build_tools = [
    "gleam",
  ], requirements = [
    "gleam_stdlib",
  ], source = "local", path = "//?/D:/git/my_app/shared" }, # <=====
# ...
]

[requirements]
shared = { path = "../shared" }
mist = { version = "~> 0.17" }
wisp = { version = "~> 0.13" }
# ...
```

It doesn't hurt when developing locally, but won't work when e.g. deploying with Docker.

_Originally posted by @xhh in https://github.com/gleam-lang/gleam/issues/2182#issuecomment-2017918389_
