### ISSUE TITLE
Check that the source code repo URL 200s when publishing and ask the user for confirmation if it does not

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2865]
To avoid typos in configuration

```toml
name = "wibble"
version = "1.0.0"
description = "wobble"
licences = ["Apache-2.0"]
repository = { type = "github", user = "wubble", repo = "oh-no-this-is-the-wrong-name" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
```
