### ISSUE TITLE
Generate GitHub actions CI configuration for new projects

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#306]

**Comment by EskiMag** [comment]
Do you have some more info about this? I am not sure I understand the usage scenario.

**Comment by lpil** [comment]
I want to make `gleam new $PROJECT` generate a `.github/workflow/whatever` file so that Gleam projects are ready for CI by default, to make reduce friction getting set up with Gleam.

An idea picked up from Crystal language

**Comment by EskiMag** [comment]
Oh, cool. Makes sense. I'll take look at it later.
A bit offtopic: could you please create new issue label to distinguish the GitHub Actions related ones, so I can better filter them?

**Comment by lpil** [comment]
It's not going to be a long-running piece of work so I don't want to create a label I'm afraid, they can't be archived.

**Comment by EskiMag** [comment]
OK, never mind then. :-)

**Comment by EskiMag** [comment]
I think we should create a `setup-gleam` action similar to this one https://github.com/actions/setup-elixir
Then the workflow would be as simple as:
```yaml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-gleam@v1.0.0
        with:
          otp-version: 22.x
          gleam-version: 0.5.x
      - run: gleam build
# and maybe later - run: gleam test
```
Am I right?
