### ISSUE TITLE
Avoid duplicate GitHub actions builds for PRs

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#309]
We build for both PR and push it seems. Make the push only build on master.

Possibly something like this:

```yaml
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
```

Currently blocked as actions doesn't seem to work on this new GitHub organisation.
