### ISSUE TITLE
[ERROR] Expected ")" but found "$"

### ISSUE THREAD

**Issue by jollmar** [gleam-lang/gleam#3412]
## Versions

* Gleam version: 1.3.1
* Mac (M2), Sonoma 14.4.1

## Steps to reproduce:
gleam.toml file contents
```toml
name = "bug"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gtempo = ">= 3.1.0 and < 4.0.0"
lustre = ">= 4.3.1 and < 5.0.0"
lustre_dev_tools = ">= 1.3.4 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
```

Content from src/bug.gleam:
```gleam
import lustre/element.{type Element}
import lustre/element/html
import tempo
import tempo/time
import lustre

pub fn main() {
  let app = lustre.simple(init, update, view)

  let assert Ok(_) = lustre.start(app, "#app", Nil)

  Nil
}

pub type Model {
  Model(time: tempo.Time)
}

fn init(_flags) -> Model {
  let assert Ok(time) = time.from_string("10:20:30")
  Model(time: time)
}

pub type Msg {}

fn update(model: Model, _msg: Msg) -> Model {
  model
}

fn view(_model: Model) -> Element(Msg) {
  html.div([], [
    element.text("Hello, World!")
  ])
}
```

Run `gleam run -m lustre/dev start`

The following error appears:

```
I ran into an unexpected issue while trying to bundle your project with esbuild.
Here's the error message I got:

    ✘ [ERROR] Expected ")" but found "$"

    build/dev/javascript/gtempo/tempo/date.mjs:238:8:
      238 │     let $ = z >= 0;
          │         ^
          ╵         )

✘ [ERROR] Could not resolve "./tempo_ffi.mjs"

    build/dev/javascript/gtempo/tempo/offset.mjs:6:46:
      6 │ import { local_offset as local_minutes } from "./tempo_ffi.mjs";
        ╵                                               ~~~~~~~~~~~~~~~~~

2 errors


If you think this is a bug, please open an issue at
https://github.com/lustre-labs/dev-tools/issues/new with some details about what
you were trying to do when you ran into this issue.
```

Happy to provide more information if needed.
