### ISSUE TITLE
Allow gleam hex.user.auth and hex.user.deauth to set a logged in user

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#3651]
Otherwise many times `gleam add wibble` where wibble is different packages will result in

`the rate limit for the Hex API has been exceeded for this IP`

**Comment by inoas** [comment]
see `mix hex.user.*`

**Comment by lpil** [comment]
Thank you

**Comment by abs0luty** [comment]
I can work on this one.

**Comment by oderwat** [comment]
For our build tool chain I have this situation when any "major" package is getting updated:

```
=== Building packages ===

Building 17 packages...

  agesec: OK
  browserlens: OK
  chrono: OK
  elog: OK
  fluxcore: OK
  glotz: OK
  hattp: OK
  ion: OK
  jwt: OK
  nanofile: OK
  omap: OK
  otelcc: OK
  pact: OK
  reflex: OK
  synapse: OK
  welo: OK
  yamco: OK

Done: 17 succeeded, 0 failed

=== Building soma ===

Building soma: SAME

=== Building cells ===

Building 27 cells...

  otelgate: OK
  tracer: OK
  tools_tester: OK
  webident: OK
  identity: OK
  webco_empty: OK
  crasher: OK
  weve__api: OK
  webco_time: 
Hex API rate limit hit. Waiting 61 seconds before retry (1/5)...
Retrying...
OK
  webco_list: OK
  rollcall: OK
  mailer: OK
  webco_shared_list: OK
  echoer: OK
  refstest: OK
  hostload_mock: OK
  weve__web: OK
  hooker: OK
  escrow: OK
  webui: OK
  weve__welogate: OK
  webse: OK
  counter: OK
  mailer_mock: OK
  hostloads: OK
  webco_personal_list: OK
  hostload: 
Hex API rate limit hit. Waiting 61 seconds before retry (1/5)...
Retrying...
OK

Done: 27 succeeded, 0 failed

All builds completed!
```

Is it really needed to contact hex on every build?
