### ISSUE TITLE
gleam new creates a project template that emits warnings when gleam test is run

### ISSUE THREAD

**Issue by ori-nonni** [gleam-lang/gleam#3930]
Gleam version 1.6.2

### How to reproduce:

Create a new hello world project
`>gleam new hello`

This creates a new project with the following `gleam.toml` :
``` toml
name = "hello"
version = "1.0.0"

# ... comment explaining features, skipped for briefness

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
```

The problem is that when I run `gleam test` I get several deprecation warnings:
```
warning: Deprecated type used
    ┌─ /[...]/gleam/hello/build/packages/gleam_stdlib/src/gleam/regex.gleam:207:17
    │
207 │   each pattern: Regex,
    │                 ^^^^^ This type has been deprecated

It was deprecated with this message: Please use the gleam_regexp package
instead
```

### Expected
`gleam new ..` should create a project that supports `gleam test` without errors.

### Workaround
To remove the warnings I needed to do `gleam add --dev gleam_regexp` . Unfortunately this is not obvious to a new user.
