### ISSUE TITLE
Ability to list extra OTP applications to be started in gleam.toml

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#650]
To be added to the list of applications in the .app file

```toml
name = "mylib"

[erlang]
extra_otp_applications = ["one", "two"]
exclude_otp_applications = ["three", "four"]
```

This would be useful for Elixir based deps as they commonly have conditional compilation that uses optional packages
